### PR TITLE
Emergency Hot Fix

### PR DESCRIPTION
**Pull request by TurtleShroom**
EMERGENCY HOT FIX.

The stupid "Bronze" mockery added by the Vanilla Factions Factions Expanded Classical Mod ( https://www.steamcommunity.com/sharedfiles/filedetails/?id=2787850474 ) was removed by the Ancient Rim series of Mods.

However, what was not factored in when I removed it was that other Mods might call it. This can crash the game or at least generate reams of unnecessary errors, so I created a "dummy" replacement to ensure the Thing Def doesn't cause problems down the line.

ALSO FIXED THE FOLLOWING ERROR:
```
Joy source joyKind and jobDef.joyKind are not the same. building=AR_2x2Fountain82696, jobDef=ViewArt
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch4 (string)
Verse.Log:ErrorOnce (string,int)
(wrapper dynamic-method) RimWorld.JoyUtility:RimWorld.JoyUtility.JoyTickCheckEnd_Patch3 (Verse.Pawn,RimWorld.JoyTickFullJoyAction,single,Verse.Building)
(wrapper dynamic-method) RimWorld.JobDriver_ViewArt:RimWorld.JobDriver_ViewArt.WaitTickAction_Patch1 (RimWorld.JobDriver_ViewArt)
RimWorld.JobDriver_VisitJoyThing:<MakeNewToils>b__2_0 ()
(wrapper dynamic-method) Verse.AI.JobDriver:Verse.AI.JobDriver.DriverTick_Patch0 (Verse.AI.JobDriver)
(wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.JobTrackerTick_Patch0 (Verse.AI.Pawn_JobTracker)
(wrapper dynamic-method) Verse.Pawn:Verse.Pawn.Tick_Patch3 (Verse.Pawn)
(wrapper dynamic-method) Verse.TickList:Verse.TickList.Tick_Patch2 (Verse.TickList)
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch9 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
Verse.Root_Play:Update ()
```

### CODE REVIEW

**Comment by emipa606** [comment]
Please dont remove files from the source-directory. If you restore them I can merge and publish it.

**Comment by TurtleShroom** [comment]
I am so sorry!
I have my PC automatically delete those to save room. I will put them right back!
--
Sent from Mail.ru app for Android Monday, 05 June 2023, 02:23PM -04:00 from Mlie  ***@***.*** :

**Comment by TurtleShroom** [comment]
Okay, I have added the source stuff back. I apologize again for the inconvenience!

**Comment by emipa606** [comment]
Should be published now, 7c9113c

**Pull request merged**
